### ISSUE TITLE
ImportError: No module named wit

### ISSUE THREAD

**Issue by dantarakan** [LoyVanBeek/wit_ros#3]
Hello @LoyVanBeek ! Thanks so much for the wit wrapper.

I've followed the instructions in the readMe file, and when executing roslaunch, I'm getting the following error:

``` sh
Traceback (most recent call last):
  File "/home/human/catkin_ws/src/wit_ros/src/wit_ros/wit_node.py", line 10, in <module>
    import wit
ImportError: No module named wit
```

Do you know what could've caused it?
Where can I get the wit module from?

Thanks,
Daniil

**Comment by LoyVanBeek** [comment]
Hi Daniil, you can get the module by $ sudo pip install wit
(See https://wit.ai/docs/python/1.0.0 of detail if needed). I updated the readme to include this. 

If I forgot anything else, please let me know

**Comment by dantarakan** [comment]
Hi Loy, thanks for the explanation, it all seems to work fine now. Good job on this!

**Comment by jalees01** [comment]
how to solve this error even if wit module is successfully installed via pip install wit

**Comment by dantarakan** [comment]
@jalees01, you might have two Python installations on your machine. Try to check that the wrapper is running on he same python installation as your pip.

**Comment by jalees01** [comment]
i have  only one python installation is in my machine

**Comment by jalees01** [comment]
i have only one python installation on my machine @dantarakan

**Comment by LoyVanBeek** [comment]
I just merged https://github.com/LoyVanBeek/wit_ros/pull/6, which updates the wrapper to a newer version of the Wit module. 

Please let me know if that works for you. If noty, please post a stack trace and I'll try to see what I can do.

**Comment by jalees01** [comment]
import wit
from wit import Wit

access_token = "xxxxxxxxxxxxxxxxx"

client = Wit(access_token = access_token)

message_text= "i want sports news"

resp =client.message(message_text)
print(resp)

**Comment by LoyVanBeek** [comment]
That looks like it should work. What's the error when you run it? (Note that this is just the Wit module, not my ROS wrapper around it)

**Comment by jalees01** [comment]
File "F:\ messenger bot\utils.py", line 1, in <module>
    import wit
ImportError: No module named 'wit'

**Comment by jalees01** [comment]
how to do that??

**Comment by LoyVanBeek** [comment]
https://github.com/wit-ai/pywit#install
