### ISSUE TITLE
ERROR: Unable to load type [wit_ros/Interpret]

### ISSUE THREAD

**Issue by airfield20** [LoyVanBeek/wit_ros#7]
When running your example command: 

> rosservice call /wit/interpret "sentence: 'Clean up the table in the living room'"

I get the output 
`ERROR: Unable to load type [wit_ros/Interpret].`
`Have you typed 'make' in [wit_ros]?`

**Comment by LoyVanBeek** [comment]
That's weird. Have you followed the steps in the README?

I just set up a branch with A Travis CI file to check the build outside of my own box.

**Comment by LoyVanBeek** [comment]
The error message is not generated by wit_ros, but by [rosservice](https://github.com/strawlab/ros_comm/blob/master/tools/rosservice/src/rosservice.py#L378). 
Is wit_ros on your ROS_PACKAGE_PATH?

**Comment by airfield20** [comment]
That was the issue, I sourced devel/setup.bash to launch in a terminal and then opened a new terminal to make the call but did not source that file again.
